sudo: required

language: cpp

services:
  - docker

env:
  - DOCKERENV=ubuntu18.04
  - DOCKERENV=archlinux

compiler:
  - clang
  - gcc

before_install:
  - docker build -t fiberio-$DOCKERENV -f ci/$DOCKERENV/Dockerfile .

script:
  - docker run --rm -e CXX fiberio-$DOCKERENV
